name: Metrics

on:
  # 每12小时自动运行一次
  schedule:
    - cron: "0 */12 * * *"
  # 每次 push 时触发(忽略 metrics 自动提交的产物,避免循环触发)
  push:
    paths-ignore:
      - "github-metrics.svg"
  # 允许手动点击按钮触发运行
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Generate self-hosted metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.PAT_TOKEN }}
          template: classic
          theme: dark
          filename: github-metrics.svg
          config_timezone: Asia/Shanghai
